### ISSUE TITLE
Animation problem from the index?

### ISSUE THREAD

**Issue by digitalsara** [digitalsara/frozen-not-in-time#1]
Hey @hellachella,

I need help understanding what Markbot is saying... It's telling me that from my Index, my ice cream cone isn't animated. In my CSS, I've placed the animation on the image classes, and added top values in the keyframes. It's animating fine when I preview it: https://digitalsara.github.io/frozen-not-in-time/

<a href="https://ibb.co/cSc1vb"><img src="https://preview.ibb.co/ku9s1G/Screen_Shot_2017_10_13_at_12_07_33_AM.png" alt="Screen_Shot_2017_10_13_at_12_07_33_AM" border="0"></a><br /><a target='_blank' href='https://imgbb.com/'></a><br />

I have one grid and two units in my Index. What is it that I'm missing?

Thank you!

**Comment by hellachella** [comment]
Hi Sara,
Hang tight, you're not the only one. It could just be Markbot.

**Comment by hellachella** [comment]
From Thomas: 

It could be related to the her "Before" screenshots.
Before the animation starts the fudge isn't positioned off screen, it's still visible on the screen.

In the `.vanilla-fudge` class the `top` coordinate should match the `top` coordinate in the `0%` keyframe.

**Comment by digitalsara** [comment]
That would make sense, since I had different values. I changed the top coordinates to go higher off the screen in my divs and matched them at 0%, only it's still telling me that it's not animated. I also fixed my before screenshots, and I still get the error...

**Comment by hellachella** [comment]
@thomasjbradley

**Comment by thomasjbradley** [comment]
It seems to be something related to the animation speed. It appears that the animation is ending before Markbot is able to grab onto it and listen to see if it moves. If I add an `animation-delay` to the fudge ice cream it works okay.

I’m exploring options in Markbot to help the problem.

**Comment by digitalsara** [comment]
I see! Thanks so much, it worked. Animation's a really cool and interesting process so far. 

Happy weekend :)

**Comment by thomasjbradley** [comment]
Okay, that's great. I was preparing a beta version of Markbot for you that works with your older code too. You can try it out here:
https://www.dropbox.com/s/pyopizjtok84h5y/Markbot.app.zip?dl=1

@hellachella Maybe you could send this to a few of the other people who are running into similar problems? I want a few more testers before I release it to everybody.

**Comment by digitalsara** [comment]
Thanks Thomas! If you need, I'd be happy to help beta test Markbot in the future, too.
